/**
 * ==========================================================================
 * config.js - الثوابت والإعدادات العامة لنظام حلقات جامع الهدى
 * ==========================================================================
 */

// 1. إعدادات Firebase (قم باستبدال البيانات أدناه ببيانات مشروعك الحقيقي عند النشر)
const FIREBASE_CONFIG = {
  apiKey: "AIzaSyDemoKey_HalaqatAlHuda2026_Project",
  authDomain: "halaqat-alhuda.firebaseapp.com",
  projectId: "halaqat-alhuda",
  storageBucket: "halaqat-alhuda.appspot.com",
  messagingSenderId: "123456789012",
  appId: "1:123456789012:web:a1b2c3d4e5f6g7h8",
};

// 2. أدوار وصلاحيات المستخدمين
const ROLES = {
  ADMIN: "admin",
  TEACHER: "teacher",
  STUDENT: "student",
};

// 3. التقديرات الافتراضية
const DEFAULT_RATINGS = ["ممتاز", "جيد جداً", "جيد", "مقبول", "ضعيف"];

// 4. الإعدادات الافتراضية للجمعية
const DEFAULT_SETTINGS = {
  orgName: "حلقات جامع الهدى لتحفيظ القرآن الكريم",
  pageSize: 20,
  sessionTimeoutMinutes: 60,
  ratings: [...DEFAULT_RATINGS],
};

// 5. قائمة سور القرآن الكريم كاملة (114 سورة) للتسميع والمراجعة
const QURAN_SURAHS = [
  { id: 1, name: "الفاتحة", verses: 7 },
  { id: 2, name: "البقرة", verses: 286 },
  { id: 3, name: "آل عمران", verses: 200 },
  { id: 4, name: "النساء", verses: 176 },
  { id: 5, name: "المائدة", verses: 120 },
  { id: 6, name: "الأنعام", verses: 165 },
  { id: 7, name: "الأعراف", verses: 206 },
  { id: 8, name: "الأنفال", verses: 75 },
  { id: 9, name: "التوبة", verses: 129 },
  { id: 10, name: "يونس", verses: 109 },
  { id: 11, name: "هود", verses: 123 },
  { id: 12, name: "يوسف", verses: 111 },
  { id: 13, name: "الرعد", verses: 43 },
  { id: 14, name: "إبراهيم", verses: 52 },
  { id: 15, name: "الحجر", verses: 99 },
  { id: 16, name: "النحل", verses: 128 },
  { id: 17, name: "الإسراء", verses: 111 },
  { id: 18, name: "الكهف", verses: 110 },
  { id: 19, name: "مريم", verses: 98 },
  { id: 20, name: "طه", verses: 135 },
  { id: 21, name: "الأنبياء", verses: 112 },
  { id: 22, name: "الحج", verses: 78 },
  { id: 23, name: "المؤمنون", verses: 118 },
  { id: 24, name: "النور", verses: 64 },
  { id: 25, name: "الفرقان", verses: 77 },
  { id: 26, name: "الشعراء", verses: 227 },
  { id: 27, name: "النمل", verses: 93 },
  { id: 28, name: "القصص", verses: 88 },
  { id: 29, name: "العنكبوت", verses: 69 },
  { id: 30, name: "الروم", verses: 60 },
  { id: 31, name: "لقمان", verses: 34 },
  { id: 32, name: "السجدة", verses: 30 },
  { id: 33, name: "الأحزاب", verses: 73 },
  { id: 34, name: "سبأ", verses: 54 },
  { id: 35, name: "فاطر", verses: 45 },
  { id: 36, name: "يس", verses: 83 },
  { id: 37, name: "الصافات", verses: 182 },
  { id: 38, name: "ص", verses: 88 },
  { id: 39, name: "الزمر", verses: 75 },
  { id: 40, name: "غافر", verses: 85 },
  { id: 41, name: "فصلت", verses: 54 },
  { id: 42, name: "الشورى", verses: 53 },
  { id: 43, name: "الزخرف", verses: 89 },
  { id: 44, name: "الدخان", verses: 59 },
  { id: 45, name: "الجاثية", verses: 37 },
  { id: 46, name: "الأحقاف", verses: 35 },
  { id: 47, name: "محمد", verses: 38 },
  { id: 48, name: "الفتح", verses: 29 },
  { id: 49, name: "الحجرات", verses: 18 },
  { id: 50, name: "ق", verses: 45 },
  { id: 51, name: "الذاريات", verses: 60 },
  { id: 52, name: "الطور", verses: 49 },
  { id: 53, name: "النجم", verses: 62 },
  { id: 54, name: "القمر", verses: 55 },
  { id: 55, name: "الرحمن", verses: 78 },
  { id: 56, name: "الواقعة", verses: 96 },
  { id: 57, name: "الحديد", verses: 29 },
  { id: 58, name: "المجادلة", verses: 22 },
  { id: 59, name: "الحشر", verses: 24 },
  { id: 60, name: "الممتحنة", verses: 13 },
  { id: 61, name: "الصف", verses: 14 },
  { id: 62, name: "الجمعة", verses: 11 },
  { id: 63, name: "المنافقون", verses: 11 },
  { id: 64, name: "التغابن", verses: 18 },
  { id: 65, name: "الطلاق", verses: 12 },
  { id: 66, name: "التحريم", verses: 12 },
  { id: 67, name: "الملك", verses: 30 },
  { id: 68, name: "القلم", verses: 52 },
  { id: 69, name: "الحاقة", verses: 52 },
  { id: 70, name: "المعارج", verses: 44 },
  { id: 71, name: "نوح", verses: 28 },
  { id: 72, name: "الجن", verses: 28 },
  { id: 73, name: "المزمل", verses: 20 },
  { id: 74, name: "المدثر", verses: 56 },
  { id: 75, name: "القيامة", verses: 40 },
  { id: 76, name: "الإنسان", verses: 31 },
  { id: 77, name: "المرسلات", verses: 50 },
  { id: 78, name: "النبأ", verses: 40 },
  { id: 79, name: "النازعات", verses: 46 },
  { id: 80, name: "عبس", verses: 42 },
  { id: 81, name: "التكوير", verses: 29 },
  { id: 82, name: "الانفطار", verses: 19 },
  { id: 83, name: "المطففين", verses: 36 },
  { id: 84, name: "الانشقاق", verses: 25 },
  { id: 85, name: "البروج", verses: 22 },
  { id: 86, name: "الطارق", verses: 17 },
  { id: 87, name: "الأعلى", verses: 19 },
  { id: 88, name: "الغاشية", verses: 26 },
  { id: 89, name: "الفجر", verses: 30 },
  { id: 90, name: "البلد", verses: 20 },
  { id: 91, name: "الشمس", verses: 15 },
  { id: 92, name: "الليل", verses: 21 },
  { id: 93, name: "الضحى", verses: 11 },
  { id: 94, name: "الشرح", verses: 8 },
  { id: 95, name: "التين", verses: 8 },
  { id: 96, name: "العلق", verses: 19 },
  { id: 97, name: "القدر", verses: 5 },
  { id: 98, name: "البينة", verses: 8 },
  { id: 99, name: "الزلزلة", verses: 8 },
  { id: 100, name: "العاديات", verses: 11 },
  { id: 101, name: "القارعة", verses: 11 },
  { id: 102, name: "التكاثر", verses: 8 },
  { id: 103, name: "العصر", verses: 3 },
  { id: 104, name: "الهمزة", verses: 9 },
  { id: 105, name: "الفيل", verses: 5 },
  { id: 106, name: "قريش", verses: 4 },
  { id: 107, name: "الماعون", verses: 7 },
  { id: 108, name: "الكوثر", verses: 3 },
  { id: 109, name: "الكافرون", verses: 6 },
  { id: 110, name: "النصر", verses: 3 },
  { id: 111, name: "المسد", verses: 5 },
  { id: 112, name: "الإخلاص", verses: 4 },
  { id: 113, name: "الفلق", verses: 5 },
  { id: 114, name: "الناس", verses: 6 },
];

// 6. مفتاح التخزين المحلي الاحتياطي LocalStorage Key
const LOCAL_STORAGE_KEY = "HALAQAT_ALHUDA_DB_V1";
